# Generated by Django 4.2 on 2023-04-18 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя клиента')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Телефонный номер')),
                ('debt', models.DecimalField(decimal_places=2, default='0', max_digits=9, verbose_name='Долг')),
                ('status', models.BooleanField(default=True, verbose_name='Статус Клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('type', models.CharField(choices=[('Diaper', 'Памперс'), ('Soap', 'Мыло'), ('Wipes', 'Влажные салфетки')], max_length=6, verbose_name='Тип товара')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Количество товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SingleConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена товара')),
                ('cost', models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Стоимость')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storage.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='SingleAdvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storage.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма прибыли')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата прибыли')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storage.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Прибыль',
                'verbose_name_plural': 'Прибыли',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая стоимость')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата расхода')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storage.client', verbose_name='Клиент')),
                ('consumption', models.ManyToManyField(to='storage.singleconsumption', verbose_name='Расход')),
            ],
            options={
                'verbose_name': 'Список расходов',
                'verbose_name_plural': 'Списки расходов',
            },
        ),
        migrations.CreateModel(
            name='AdventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата прихода')),
                ('advent', models.ManyToManyField(to='storage.singleadvent', verbose_name='Приход')),
            ],
            options={
                'verbose_name': 'Список приходов',
                'verbose_name_plural': 'Списки приходов',
            },
        ),
    ]
