# Generated by Django 4.2 on 2023-04-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя клиента')),
                ('status', models.BooleanField(default=True, verbose_name='Статус Клиента')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Телефонный номер')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('type', models.CharField(choices=[('Diaper', 'Памперс'), ('Soap', 'Мыло'), ('Wipes', 'Влажные салфетки')], max_length=6, verbose_name='Тип товара')),
                ('balance', models.PositiveIntegerField(verbose_name='Остаток товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_of_profit', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма прибыли')),
                ('date_of', models.DateField(auto_now_add=True, verbose_name='Дата прибыли')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Прибыль',
                'verbose_name_plural': 'Прибыли',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена товара')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('sum', models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Общая сумма')),
                ('date_of', models.DateField(auto_now_add=True, verbose_name='Дата расхода')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='storage.client', verbose_name='Клиент')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='storage.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Advent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('date_of', models.DateField(auto_now_add=True, verbose_name='Дата прихода')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
    ]
