# Generated by Django 4.1 on 2022-08-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя клиента')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Телефонный номер')),
                ('debt', models.FloatField(verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('type', models.CharField(choices=[('D', 'Памперс'), ('S', 'Мыло'), ('W', 'Влажные салфетки')], max_length=1, verbose_name='Тип товара')),
                ('balance', models.FloatField(verbose_name='Остаток товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='MinusDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_of_minus', models.FloatField(verbose_name='Сумма минуса долга')),
                ('date_of', models.DateField(auto_now_add=True, verbose_name='Дата минуса долга')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Минус от клиента',
                'verbose_name_plural': 'Минусы от клиента',
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество товара')),
                ('sum', models.FloatField(editable=False, verbose_name='Общая сумма')),
                ('date_of', models.DateField(auto_now_add=True, verbose_name='Дата расхода')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество товара')),
                ('date_of', models.DateField(auto_now_add=True, verbose_name='Дата прихода')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
    ]
