# Generated by Django 4.1.6 on 2023-02-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minusdebt',
            options={'verbose_name': 'Прибыль', 'verbose_name_plural': 'Прибыли'},
        ),
    ]
