# Generated by Django 4.1.6 on 2023-02-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_minusdebt_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckIn',
            new_name='Advent',
        ),
        migrations.RenameModel(
            old_name='CheckOut',
            new_name='Consumption',
        ),
        migrations.RenameModel(
            old_name='MinusDebt',
            new_name='Profit',
        ),
    ]
