# Generated by Django 4.1.6 on 2023-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_rename_checkin_advent_rename_checkout_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='sum_of_minus',
        ),
        migrations.AddField(
            model_name='profit',
            name='sum_of_profit',
            field=models.FloatField(default=0, verbose_name='Сумма прибыли'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='date_of',
            field=models.DateField(auto_now_add=True, verbose_name='Дата прибыли'),
        ),
    ]
