# Generated by Django 3.2.17 on 2023-02-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_profit_sum_of_minus_profit_sum_of_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус Клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Долг'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='sum',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Остаток товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Diaper', 'Памперс'), ('Soap', 'Мыло'), ('Wipes', 'Влажные салфетки')], max_length=6, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='sum_of_profit',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма прибыли'),
        ),
    ]
